# Generated by Django 3.1.5 on 2021-01-23 22:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210123_2154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0002_auto_20210123_2112'),
        ('profiles', '0003_auto_20210123_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
