# Generated by Django 3.1.5 on 2021-01-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210123_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
    ]
