# Generated by Django 3.1.5 on 2021-01-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0007_auto_20210120_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Membership Picture')),
                ('first_order_disc', models.IntegerField(default=0, verbose_name='First Order Discount')),
                ('overall_discount', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Med', 'Medium'), ('Low', 'Low')], help_text='Priority of announcements', max_length=10)),
                ('q_gift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quarterly Gift')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('free_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.deliverytype')),
            ],
        ),
    ]
