# Generated by Django 3.1.5 on 2021-01-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='est_deliery_dte',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='estimated order delivery date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='est_dispatch_dte',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='estimated order dispatch date'),
        ),
    ]
