# Generated by Django 3.1.5 on 2021-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=70),
        ),
    ]
