# Generated by Django 3.1.5 on 2021-01-10 20:13

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color_hex', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('many_colors', models.BooleanField(default=False)),
                ('main_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='')),
                ('added_date', models.DateField(auto_now_add=True)),
                ('release_date', models.DateTimeField(default=models.DateField(auto_now_add=True))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
