# Generated by Django 3.1.5 on 2021-01-10 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210110_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 21, 5, 21, 470373, tzinfo=utc)),
        ),
    ]
