# Generated by Django 3.1.5 on 2021-01-11 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210111_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(help_text='Select today/now as the input if the product is being published now.', verbose_name='product release date'),
        ),
    ]
