# Generated by Django 3.1.5 on 2021-01-15 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
